### ISSUE TITLE
Allowing more keyword arguments for create_biv_ellipsoid

### ISSUE THREAD

**Issue by Reidmen** [ComputationalPhysiology/cardiac_geometries#13]
* Python version: 3.8
* Operating System:  Ubuntu 20.04.6 LTS

### Description

As a user, I have a case with a bi-ventricular domain that requires the center `center_rv_z` to be non zero. Is there a reason to limit users keyword arguments to only the y-direction of the centers when executing `create_biv_ellipsoid`?

PD: I implemented workaround in a branch allowing more options to the users.

**Comment by finsberg** [comment]
There is no reason to limit users keyword arguments to only the y-direction. The reason it is only implemented for the y-direction was because this was what I needed when creating the library. PRs are welcomed 😊
